import { Metadata } from "next";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import BackBtn from "@/components/back-btn";
import ForgotPasswordForm from "@/components/forgot-form";

export const metadata: Metadata = {
	title: "Forgot Password",
	description: "Generated by create next app",
};

const ForgotPassword = () => {
	return (
		<section className="h-screen flex items-center justify-center">
			<Card className="mx-auto max-w-sm z-10">
				<CardHeader>
					<CardTitle className="text-2xl">Trouble logging in?</CardTitle>
					<CardDescription>
						Enter your email, and we&apos;ll send you a link to get back into your account
					</CardDescription>
				</CardHeader>

				<CardContent>
					<div className="grid gap-4">
						<ForgotPasswordForm />

						<BackBtn />
					</div>
				</CardContent>
			</Card>
		</section>
	);
};
export default ForgotPassword;
