import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";

import Background from "@/components/background";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
	title: {
		template: "%s • GateKeep",
		default: "GateKeep",
	},
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={GeistSans.className}>
			<body>
				<Background />
				{children}
				<Toaster />
			</body>
		</html>
	);
}
