import Link from "next/link";
import { Metadata } from "next";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

import ResendBtn from "@/components/resend-btn";
import BackBtn from "@/components/back-btn";
import OtpForm from "@/components/otp-form";

import { searchParams } from "@/types";

export const metadata: Metadata = {
	title: "Verification",
	description: "Generated by create next app",
};

const VerifyEmail = ({ searchParams }: searchParams) => {
	const email = searchParams.email;

	return (
		<section className="h-screen flex items-center justify-center">
			<Card className="mx-auto max-w-sm z-10">
				<CardHeader>
					<CardTitle className="text-xl">Email Verification</CardTitle>
					<CardDescription>Please enter the one-time password sent to {email}.</CardDescription>
					<CardDescription className="!mt-1">
						Didn&apos;t get the email? <ResendBtn email={`${email}`} />
					</CardDescription>
				</CardHeader>

				<CardContent>
					<div className="grid gap-4">
						<div className="flex flex-col gap-4 items-center">
							<OtpForm email={`${email}`} />

							<BackBtn />
						</div>

						<div className="text-center text-sm">
							Already have an account?{" "}
							<Link
								href="/login"
								className="underline">
								Sign in
							</Link>
						</div>
					</div>
				</CardContent>
			</Card>
		</section>
	);
};
export default VerifyEmail;
