import Link from "next/link";
import { Metadata } from "next";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import GoggleBtn from "@/components/goggle-btn";
import GithubBtn from "@/components/github-btn";
import LoginForm from "@/components/login-form";

export const metadata: Metadata = {
	title: "Login",
	description: "Generated by create next app",
};

export default function LoginPage() {
	return (
		<section className="h-screen flex items-center justify-center">
			<Card className="mx-auto max-w-sm z-10">
				<CardHeader>
					<CardTitle className="text-2xl">Login</CardTitle>
					<CardDescription>Enter your email below to login to your account</CardDescription>
				</CardHeader>

				<CardContent>
					<div className="grid gap-4">
						<LoginForm />

						<div className="flex items-center w-full gap-x-2">
							<GoggleBtn />

							<GithubBtn />
						</div>
					</div>

					<div className="mt-4 text-center text-sm">
						Don&apos;t have an account?{" "}
						<Link
							href="/signup"
							className="underline">
							Sign up
						</Link>
					</div>
				</CardContent>
			</Card>
		</section>
	);
}
