import Link from "next/link";
import { Metadata } from "next";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import GoggleBtn from "@/components/goggle-btn";
import GithubBtn from "@/components/github-btn";
import SignupForm from "@/components/signup-form";

export const metadata: Metadata = {
	title: "Signup",
	description: "Generated by create next app",
};

export default function SignupPage() {
	return (
		<section className="h-screen flex items-center justify-center">
			<Card className="mx-auto max-w-sm z-10">
				<CardHeader>
					<CardTitle className="text-xl">Sign Up</CardTitle>
					<CardDescription>Enter your information to create an account</CardDescription>
				</CardHeader>

				<CardContent>
					<div className="grid gap-4">
						<SignupForm />

						<div className="flex items-center w-full gap-x-2">
							<GoggleBtn />

							<GithubBtn />
						</div>
					</div>

					<div className="mt-4 text-center text-sm">
						Already have an account?{" "}
						<Link
							href="/login"
							className="underline">
							Sign in
						</Link>
					</div>
				</CardContent>
			</Card>
		</section>
	);
}
